### ISSUE TITLE
Add support for node 16.x

### ISSUE THREAD

**Issue by ransonhobbes** [ransonhobbes/stardust#12]
Running `node ci` currently fails on node16 with the following. Upgrading the version of truffle that azimuth-solidity relies on might fix it.

```
2021-06-25T20:39:12.4992178Z npm ERR! code 1
2021-06-25T20:39:12.4994202Z npm ERR! path /home/runner/work/stardust/stardust/node_modules/azimuth-solidity
2021-06-25T20:39:12.5011412Z npm ERR! command failed
2021-06-25T20:39:12.5012728Z npm ERR! command sh -c npm run build
2021-06-25T20:39:12.5013947Z npm ERR! > azimuth-solidity@1.2.2 build
2021-06-25T20:39:12.5014814Z npm ERR! > truffle compile
2021-06-25T20:39:12.5025682Z npm ERR! 
2021-06-25T20:39:12.5040688Z npm ERR! 
2021-06-25T20:39:12.5041293Z npm ERR! Compiling your contracts...
2021-06-25T20:39:12.5041836Z npm ERR! ===========================
2021-06-25T20:39:12.5042476Z npm ERR! > Compiling ./contracts/Azimuth.sol
2021-06-25T20:39:12.5384823Z npm ERR! > Compiling ./contracts/Censures.sol
2021-06-25T20:39:12.5385693Z npm ERR! > Compiling ./contracts/Claims.sol
2021-06-25T20:39:12.5386750Z npm ERR! > Compiling ./contracts/ConditionalStarRelease.sol
2021-06-25T20:39:12.5387902Z npm ERR! > Compiling ./contracts/DelegatedSending.sol
2021-06-25T20:39:12.5388870Z npm ERR! > Compiling ./contracts/ENSRegistry.sol
2021-06-25T20:39:12.5389745Z npm ERR! > Compiling ./contracts/Ecliptic.sol
2021-06-25T20:39:12.5390627Z npm ERR! > Compiling ./contracts/EclipticBase.sol
2021-06-25T20:39:12.5435672Z npm ERR! > Compiling ./contracts/EclipticResolver.sol
2021-06-25T20:39:12.5437519Z npm ERR! > Compiling ./contracts/LinearStarRelease.sol
2021-06-25T20:39:12.5438636Z npm ERR! > Compiling ./contracts/Migrations.sol
2021-06-25T20:39:12.5439895Z npm ERR! > Compiling ./contracts/NFTokenReceiverTestMock.sol
2021-06-25T20:39:12.5441123Z npm ERR! > Compiling ./contracts/PlanetSale.sol
2021-06-25T20:39:12.5442087Z npm ERR! > Compiling ./contracts/Polls.sol
2021-06-25T20:39:12.5443127Z npm ERR! > Compiling ./contracts/PublicResolver.sol
2021-06-25T20:39:12.5444223Z npm ERR! > Compiling ./contracts/ReadsAzimuth.sol
2021-06-25T20:39:12.5445244Z npm ERR! > Compiling ./contracts/SafeMath16.sol
2021-06-25T20:39:12.5446241Z npm ERR! > Compiling ./contracts/SafeMath8.sol
2021-06-25T20:39:12.5447325Z npm ERR! > Compiling ./contracts/TakesPoints.sol
2021-06-25T20:39:12.5449222Z npm ERR! > Compiling ./contracts/interfaces/ENS.sol
2021-06-25T20:39:12.5451114Z npm ERR! > Compiling ./contracts/interfaces/ResolverInterface.sol
2021-06-25T20:39:12.5452890Z npm ERR! > Compiling openzeppelin-solidity/contracts/AddressUtils.sol
2021-06-25T20:39:12.5454371Z npm ERR! > Compiling openzeppelin-solidity/contracts/introspection/ERC165.sol
2021-06-25T20:39:12.5456572Z npm ERR! > Compiling openzeppelin-solidity/contracts/introspection/SupportsInterfaceWithLookup.sol
2021-06-25T20:39:12.5458300Z npm ERR! > Compiling openzeppelin-solidity/contracts/math/SafeMath.sol
2021-06-25T20:39:12.5459717Z npm ERR! > Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol
2021-06-25T20:39:12.5461169Z npm ERR! > Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721.sol
2021-06-25T20:39:12.5462586Z npm ERR! > Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721Basic.sol
2021-06-25T20:39:12.5463913Z npm ERR! > Compiling openzeppelin-solidity/contracts/token/ERC721/ERC721Receiver.sol
2021-06-25T20:39:12.5464876Z npm ERR! RangeError: Maximum call stack size exceeded
2021-06-25T20:39:12.5466422Z npm ERR!     at Object._db [as dynCall_viiiiii] (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:12:120931)
2021-06-25T20:39:12.5468205Z npm ERR!     at invoke_viiiiii (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:1:1117622)
2021-06-25T20:39:12.5469926Z npm ERR!     at Array.ova (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:13:29030)
2021-06-25T20:39:12.5472263Z npm ERR!     at Object.L9a [as dynCall_vi] (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:12:99033)
2021-06-25T20:39:12.5474277Z npm ERR!     at invoke_vi (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:1:1114426)
2021-06-25T20:39:12.5476215Z npm ERR!     at Array.wta (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:10:704789)
2021-06-25T20:39:12.5478527Z npm ERR!     at Object.Cfb [as dynCall_iii] (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:12:130740)
2021-06-25T20:39:12.5480510Z npm ERR!     at invoke_iii (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:1:1118857)
2021-06-25T20:39:12.5482460Z npm ERR!     at Array.uta (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:10:703085)
2021-06-25T20:39:12.5484542Z npm ERR!     at Object.Xfb [as dynCall_iiiiii] (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:12:131900)
2021-06-25T20:39:12.5486818Z npm ERR!     at invoke_iiiiii (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:1:1119107)
2021-06-25T20:39:12.5488877Z npm ERR!     at yua (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:10:861324)
2021-06-25T20:39:12.5490891Z npm ERR!     at qra (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:10:535869)
2021-06-25T20:39:12.5492936Z npm ERR!     at Array.oqa (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:10:461143)
2021-06-25T20:39:12.5495165Z npm ERR!     at Object.zhb [as dynCall_iiiii] (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:12:139268)
2021-06-25T20:39:12.5497355Z npm ERR!     at invoke_iiiii (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:1:1120221)
2021-06-25T20:39:12.5499486Z npm ERR!     at Array.Zpa (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:10:406357)
2021-06-25T20:39:12.5501553Z npm ERR!     at Object.wjb [as dynCall_viiii] (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:12:147059)
2021-06-25T20:39:12.5503435Z npm ERR!     at invoke_viiii (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:1:1121512)
2021-06-25T20:39:12.5505144Z npm ERR!     at Array.Zpa (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:10:403171)
2021-06-25T20:39:12.5506952Z npm ERR!     at Object.wjb [as dynCall_viiii] (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:12:147059)
2021-06-25T20:39:12.5508822Z npm ERR!     at invoke_viiii (/home/runner/.config/truffle/compilers/node_modules/soljson-v0.4.24+commit.e67f0147.js:1:1121512)
2021-06-25T20:39:12.5509763Z npm ERR! Truffle v5.3.6 (core: 5.3.6)
2021-06-25T20:39:12.5510212Z npm ERR! Node v16.4.0
2021-06-25T20:39:12.5511010Z npm ERR! - Fetching solc version list from solc-bin. Attempt #1
2021-06-25T20:39:12.5512487Z npm ERR! ✔ Downloading compiler. Attempt #1.
```

**Comment by OdysLam** [comment]
Is truffle required, since you use hardhat already.

**Comment by ransonhobbes** [comment]
Nope, we use hardhat in place of truffle. Truffle is used by some of the underlying libraries including azimuth, however.

**Comment by OdysLam** [comment]
`npm ci` worked just fine in both stardust and azimuth repos.
```
 odys@odys-mbp-68  ~/github/stardust   main  npm -v
7.15.1
 odys@odys-mbp-68  ~/github/stardust   main  node -v
v16.3.0
```

**Comment by ransonhobbes** [comment]
This is happening again. There's more info here: https://stackoverflow.com/questions/67782232/compiling-solidity-error-rangeerror-maximum-call-stack-size-exceeded. I was able to resolve it by running `npm uninstall solc`.

**Comment by ransonhobbes** [comment]
Still unable to get this to work reliably with node16. It's working with node14.
